imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    port:       "%mailer_port%"
    encryption: "%mailer_encryption%"
    spool:     { type: memory }
    disable_delivery:  true

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    registration:
        form:
            type: UserBundle\Form\Type\RegistrationType
    profile:
        form:
            type: UserBundle\Form\Type\ProfileFormType
    resetting:
        email:
            from_email:
                address:        "%mailer_user%"
                sender_name:    "%mailer_resetting_name%"
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.block.service.text:
            contexts: [admin]
sonata_admin:
    templates:
        layout: VimoliaBundle:Admin:standard_layout.html.twig
        dashboard: VimoliaBundle:Admin:dashboard.html.twig
        action: SonataAdminBundle:CRUD:action.html.twig
    dashboard:
        groups:
            User:
                on_top:               false
                label:                Utilisateurs
                label_catalogue:      ~
                items:
                    - admin.user
                    - admin.certifications
            Domaines:
                on_top:               true
                label:                Domaines
                label_catalogue:      ~
                items:
                    - admin.practdomains
            Partenaires:
                on_top:               true
                label:                Partenaires
                label_catalogue:      ~
                items:
                    - admin.partners
            Suscribe:
                on_top:               true
                label:                Abonnements
                label_catalogue:      ~
                items:
                    - admin.subscribe
         #  Video:
         #      on_top:               true
         #      label:                Vidéo
         #      label_catalogue:      ~
         #      items:
         #          - admin.video

         #   A propos de nous:
         #       on_top:               false
         #       label:                A propos de nous
         #       label_catalogue:      ~
         #       items:
         #           - admin.aboutus
         #           - admin.cgu
      # blocks:
      #     -
      #         position: center
      #         type: sonata.admin.block.admin_list
      #         settings:
      #             groups: [User, A propos de nous]
      #     -
      #         position: right
      #         type: sonata.admin.block.admin_list
      #         settings:
      #             groups: [Partners, Article, Video]
      #     -
      #         position: left
      #         type: sonata.block.service.text
      #         settings:
      #             content: >
      #                 <h2>Bienvenue sur la page d'administration du site</h2>
      #                 <p>Dashboard Admin</p>
services:
  twig.extension.date:
       class: Twig_Extensions_Extension_Date
       tags:
           - { name: twig.extension }

  twig.extension.intl:
      class: Twig_Extensions_Extension_Intl
      tags:
          - { name: twig.extension }

knp_paginator:
    page_range: 15                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
