# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
        class: UserBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: UserBundle\Form\Type\ProfileFormType
        tags:
            - { name: form.type, alias: app_user_profile }

    paypal_interface:
        class: UserBundle\Services\PaypalInterface
        arguments: ["%paypal_client_id%","%paypal_client_secret%","%paypal_mode%","%paypal_taxe_percent%","@router"]

    admin.user:
            class: VimoliaBundle\Admin\UserAdmin
            arguments: [~, UserBundle\Entity\User, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Utilisateurs }

    admin.cgu:
            class: VimoliaBundle\Admin\CguAdmin
            arguments: [~, VimoliaBundle\Entity\Cgu, ~]
            tags:
               - { name: sonata.admin, manager_type: orm, label: Cgu }

    admin.partners:
            class: VimoliaBundle\Admin\PartnersAdmin
            arguments: [~, VimoliaBundle\Entity\Partners, ~]
            tags:
              - { name: sonata.admin, manager_type: orm, label: Partenaires }

    admin.aboutus:
            class: VimoliaBundle\Admin\AboutUsAdmin
            arguments: [~, VimoliaBundle\Entity\Aboutus, ~]
            tags:
              - { name: sonata.admin, manager_type: orm, label: AboutUs }

    admin.certifications:
            class: VimoliaBundle\Admin\CertificationsAdmin
            arguments: [~, VimoliaBundle\Entity\Certification, ~]
            tags:
              - { name: sonata.admin, manager_type: orm, label: Certifications }

    admin.video:
            class: VimoliaBundle\Admin\VideoAdmin
            arguments: [~, VimoliaBundle\Entity\Video, ~]
            tags:
              - { name: sonata.admin, manager_type: orm, label: Vidéos }
           # calls:
            #  - [ setTemplate, [list, SonataAdminBundle:VideoAdmin:youtube.html.twig]]

    admin.article:
            class: VimoliaBundle\Admin\ArticleAdmin
            arguments: [~, VimoliaBundle\Entity\Article, ~]
            tags:
              - { name: sonata.admin, manager_type: orm, label: Article }

    admin.discussion:
                class: VimoliaBundle\Admin\DiscussionAdmin
                arguments: [~, VimoliaBundle\Entity\Discussion, ~]
                tags:
                  - { name: sonata.admin, manager_type: orm, label: Discussion }
    admin.practdomains:
                class: VimoliaBundle\Admin\PractDomaineAdmin
                arguments: [~, VimoliaBundle\Entity\Practdomains, ~]
                tags:
                  - { name: sonata.admin, manager_type: orm, label: Domaines }
    admin.subscribe:
                class: VimoliaBundle\Admin\SubscribeAdmin
                arguments: [~, VimoliaBundle\Entity\subscribetype, ~]
                tags:
                  - { name: sonata.admin, manager_type: orm, label: Abonnements }