<?php

namespace UserBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function findPracts($domain = null)
	{
		$qb = $this->createQueryBuilder('ac');
		$query = $this->createQueryBuilder('a')
		              ->select('a')
		              ->where('a.enabled = 1')
					  ->andWhere('a.practValid = 1');

			if($domain != null)
			{
				$query->leftJoin('a.practinfos', 'c');
				$query->leftJoin('c.practDomains', 'd')
				->andWhere($qb->expr()->in('d', ':d'))
				->setParameter('d', $domain);
			}

		return $query->getQuery()
		             ->getResult();
	}
}
