<?php

namespace VimoliaBundle\Repository;

/**
 * DiscoveryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscoveryTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
